### ISSUE TITLE
Difficulty generating valid SAM records

### ISSUE THREAD

**Issue by adbeggs** [ucagenomix/sicelore#10]
Hi

Thank you for the useful tool! I've managed to get through most of the vignette however when trying to generate an isoform matrix it appears allof the SAM records are "invalid" - I don't quite understand what invalid means in this context.

Here is an example SAM record (from molecules.GE.tags.bam):

> GAGTGTTGTTAACCTG-GGTAGCCTACTT-2	16	chr1	826077	55	5M1D56M1D15M2D30M1D8M1D73M1D101M1D79M2D42M1D48M1D23M1I9M1I32M2I19M1D4M1I38M1I49M1I29M1I67M1D49M1I19M1D103M1D33M1I13M4D11M1I6M1D25M1D8M1D13M1D20M1I2M1D36M1I129M1I11M1D14M4I27M2I6M2D53M1D31M1I10M2S	*	0	0	CACGGTTTAATCATATTGATTAAAAGCATTTGTCTTCTCCAGAACATCACATTAAGTCATCAAAAATATAAACCTTAAAGATGTAATTATTGGAACTGAAAAACATAAAGATGACTTTGGAAATATCTTTGAGCAATTTATTCGTTATGAACACATGTAATCTGTTGGAACAAAGTTCTAGGACAATCAATTCATCCTTCAATATTTTCAGAAAACATCACAAAGAAAACTTGATACTTATGCTTAGTTGGAAACTTTATGCCACAGCTATTAAATACAGAGATCATATAAGGAATAGAGGAAGCTGTTGAATACTAAACTAACTCAAATCATCATTATCCTTACAGAGTGCACACTGAATTAATGTAAAGCATTTAGTAAACAAAAAGTATTTTCAATATACAATTGAACTGAAAAGTATTGAGGCCTCATAAGCTGAACCTGACACAATAAATTTAAAGGGAAACTAATTTGGAAATCAAGAAAGCCATCTAAGGAATTTGGGAATTAGGCTTCTGCTGCCCTCTCTCTGCTACTGACGGTCAGGCACTCCTCATTGTATTCTGTCCTCCATATCTCTGCTGATTCCCCATTTTGTCTATTTCCATTTACCCCACTACTGCTTGCTCAGGTCACTCCTCCTTCACTGTCAGTGTTTGTTCAAATTCCCTCAGACCCATCCACTTCCCATCTAAACTTCCCTCCCCTTTTCTCGCTCATTGGCTCTACCTCCCTCTCTCTGTTTTCTCCTCACTCTCCTGCCCCACCTCGACATCCACAGCGAGGGCAATGAAGAAGCCCCTGCGAGGAAGAGCCCGCTTCTCAGTGGGACACCGGGAAGGTAGACACCCAACAGTCACCGCTAGTGGGAGGCGATTGTGCAGAAGCACGAGGGTTGTTACAGGATGGGCAGGTCCCCTACCCCAGTCTCGGACTCAGGAGTCCTGTCTGAGGCAGCCTGAAGCAGTAGGGTTGCGGGGCAATAGGGCCTGGCGGAGGAAGGACGGGAAGCATCTCAGGAGGACTGGCGTCTGCCGAGATCCAGGGCTGCCCTGAGGGGCCAAGAGGGGCGAGGGTGGGGGACGATGGAAGACAAGCCACATGCCGAATGGGGACCTGACGCGGCGCGCGACGGGATGGGCGGACGGTGAAGAGAACTAGGGAGGAAGGGCCGGACAGGGGCGACCTCAGTGACGGAACCGGACACGAAAGGCAGATCAGCAGCTGAGCGACGCGGAAGCTTCGGAGCATTTCCGGGCGTCGCGGGGGACTCCGCCGACAGGAGGGCGGTTGCCGAGCCTGTGACATCCGCGGAGACCAGCAGACCCAGGTGTGGAGGACGCCGCAGGGAGGGGAGCTGCGTGGCTCC	*	s1:i:933	s2:i:854	U8:Z:GGTAGCCTACTT	BC:Z:GAGTGTTGTTAACCTG	GE:Z:LINC00115	XF:Z:UTR	NM:i:82	RN:i:2	AS:i:1122	GS:Z:-	de:f:0.0513	rl:i:0	cm:i:125	nn:i:0	tp:A:P	ms:i:1122	ts:A:+

And is here the example output:

```
java -jar -Xmx44g /storage2/software/sicelore/Jar/Sicelore-1.0.jar IsoformMatrix I=molecules.GE.tags.bam REFFLAT=refFlat.txt CSV=../FirstLipoSarcoma-defaultcells/outs/barcodes.tsv DELTA=2 MAXCLIP=150 METHOD=SCORE AMBIGUOUS_ASSIGN=true OUTDIR=. PREFIX=sicelore
[Mon Mar 30 14:36:13 UTC 2020] IsoformMatrix INPUT=molecules.GE.tags.bam REFFLAT=refFlat.txt CSV=../FirstLipoSarcoma-defaultcells/outs/barcodes.tsv DELTA=2 OUTDIR=. PREFIX=sicelore METHOD=SCORE MAXCLIP=150 AMBIGUOUS_ASSIGN=true    ISOBAM=false CELLTAG=BC UMITAG=U8 GENETAG=IG TSOENDTAG=TE UMIENDTAG=UE POLYAENDTAG=PE USTAG=US RNTAG=RN VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Mon Mar 30 14:36:13 UTC 2020] Executing as beggsa@fuggle on Linux 4.15.0-91-generic amd64; OpenJDK 64-Bit Server VM 11.0.6+10-post-Ubuntu-1ubuntu118.04.1; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: null
INFO	2020-03-30 14:36:13	IsoformMatrix		Cells detected		[216]
INFO	2020-03-30 14:36:13	UCSCRefFlatParser	UCSCRefFlatParser	start...
INFO	2020-03-30 14:36:14	UCSCRefFlatParser	UCSCRefFlatParser	end...
INFO	2020-03-30 14:36:14	UCSCRefFlatParser	Number of Genes Symbols	[28253]
INFO	2020-03-30 14:36:14	UCSCRefFlatParser	Number of Transcripts	[75296]
INFO	2020-03-30 14:36:14	LongreadParser		start...
INFO	2020-03-30 14:36:29	LongreadParser		end...
INFO	2020-03-30 14:36:29	LongreadParser		Total SAMrecords	[354019]
INFO	2020-03-30 14:36:29	LongreadParser		SAMrecords valid	[0]
INFO	2020-03-30 14:36:29	LongreadParser		SAMrecords unvalid	[354019]
INFO	2020-03-30 14:36:29	LongreadParser		SAMrecords mapqv=0	[0]
INFO	2020-03-30 14:36:29	LongreadParser		SAMrecords no gene	[352662]
INFO	2020-03-30 14:36:29	LongreadParser		SAMrecords no UMI	[0]
INFO	2020-03-30 14:36:29	LongreadParser		SAMrecords chimeria	[1357]
INFO	2020-03-30 14:36:29	LongreadParser		SAMrecords reversed	[0]
INFO	2020-03-30 14:36:29	LongreadParser		Total reads		[0]
INFO	2020-03-30 14:36:29	LongreadParser		Total reads multiSAM	[0]
INFO	2020-03-30 14:36:29	MoleculeDataset		Total Molecules		[0]
INFO	2020-03-30 14:36:29	MoleculeDataset		Total Molecules multiIG	[0]
INFO	2020-03-30 14:36:29	MoleculeDataset		SetIsoforms		start...
INFO	2020-03-30 14:36:29	MoleculeDataset		SetIsoforms		end...
INFO	2020-03-30 14:36:29	MoleculeDataset		SetIsoforms		monoexon	[0]
INFO	2020-03-30 14:36:29	MoleculeDataset		SetIsoforms		no match	[0]
INFO	2020-03-30 14:36:29	MoleculeDataset		SetIsoforms		one match	[0]
INFO	2020-03-30 14:36:29	MoleculeDataset		SetIsoforms		ambiguous	[0]
INFO	2020-03-30 14:36:29	MoleculeDataset		DTEMatrix		start...[28253] genes
INFO	2020-03-30 14:36:29	MoleculeDataset		DTEMatrix		[10000/28253] genes processed
INFO	2020-03-30 14:36:29	MoleculeDataset		DTEMatrix		[20000/28253] genes processed
INFO	2020-03-30 14:36:29	MoleculeDataset		DTEMatrix		[28253/28253] genes processed
INFO	2020-03-30 14:36:29	IsoformMatrix		writeJunctionMatrix	[start]
INFO	2020-03-30 14:36:29	IsoformMatrix		writeIsoformMatrix	[start]
INFO	2020-03-30 14:36:29	IsoformMatrix		writeGeneMatrix		[start]
INFO	2020-03-30 14:36:29	IsoformMatrix		writeCellMetrics	[start]
INFO	2020-03-30 14:36:29	IsoformMatrix		Matrix cells size	[216]
INFO	2020-03-30 14:36:29	IsoformMatrix		Matrix genes size	[0]
INFO	2020-03-30 14:36:29	IsoformMatrix		Matrix junctions size	[0]
INFO	2020-03-30 14:36:29	IsoformMatrix		Matrix isoforms size	[0]
INFO	2020-03-30 14:36:29	IsoformMatrix		Matrix isoforms counts	[0]
INFO	2020-03-30 14:36:29	IsoformMatrix		Matrix isoforms define	[0]

```

**Comment by adbeggs** [comment]
Actually problem solved - the vignette needs a GENETAG=GE appended to the command for it to work

**Comment by ucagenomix** [comment]
i changeg the default value to GENETAG=GE and add it to the command line vignette,
thanks
