### ISSUE TITLE
Confusion between matrix and molinfos file from SNP calling?

### ISSUE THREAD

**Issue by ahawkins1992** [ucagenomix/sicelore#11]
Hello, I am trying to clarify the outputs from the SNPMatrix function. 

For the matrix output, I have values corresponding to cell barcodes that are >0 suggesting that there should be cells that contain the SNP found correct?  It is my impression that this number represents the total reads containing the mutation for each cell barcode? 

However, in the molinfos file, the column for passed reads is a list of all 0s? If this is the breakdown of reads with mutations/ UMI wouldn't this have to have some passed reads if there are reads in the matrix file that are being counted? 

Just wanted to make sure I am understanding the output correctly. Thank you!

**Comment by ucagenomix** [comment]
In  the latest version of SNPmatrix there's 3 output files:
- the matrix output:
`geneId  transcriptId    exon    GCCTAGCGATCTGACC ....`
`name     chr:position..A  na   2...`

meaning that 2 molecules in cell GCCTAGCGATCTGACC have a A base at SNP position
you will get 4 lines (A/T/C/G) per SNP position if all nt. are observed at least once

- the metrics output:
`geneId  transcriptId    exon    count`
`name     chr:position..A    na      5`

meaning 5 molecules in all cells have been seen with a A at SNP position

- the molinfos output:
`cellBarcode     UMI     total_reads     supporting_reads        geneId  transcriptId`
`TCCCGGGTGTGCTGCT        CAGTGCTTGTCG    1       0       name      chr:position..A`

one line per each molecule (cellBarcode/UMI) that have been seen at the SNPs list processed, total_reads is RN tag of molecule, supporting_read is useless, this is for IsoformMatrix pipeline.

Hope this helps !

**Comment by ahawkins1992** [comment]
Makes complete sense. Thank you so much for clarifying!
