### ISSUE TITLE
Expired jar files

### ISSUE THREAD

**Issue by perllb** [ucagenomix/sicelore#12]
Hi, 
I am trying to run the sicelore pipeline, but I am getting the error messages below.

I tried to git clone sicelore again, but I get the same error. They worked last Friday (3rd April 2020). Other jars in the sicelore package seems to work. I would be grateful for your help.

>   +++++++   NanoporeBC_UMI_finder 1.002  Build Dec 27, 2019++++++++++++
>   ****************************************************************************************************************************************
>   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  EXPIRED 2020-04-04 - Download a new version from Github !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
>   ****************************************************************************************************************************************
> 

And (this happens when running 
> java -Xmx15000m -jar /opt/bin/sicelore/Jar/IlluminaParser-1.0.jar ...
But works with 
> > java -Xmx15000m -jar /opt/bin/sicelore/Jar/IlluminaParser-1.0**02**.jar ...

> 
> +++++++   ILLUMINAPARSER 1.002_1  Build Dec 17, 2019++++++++++++
> ****************************************************************************************************************************************
> !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  EXPIRED 2020-04-04 - Download a new version from Github !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
> ****************************************************************************************************************************************

**Comment by ucagenomix** [comment]
Expiry date has been removed, re-clone the repository it should works now.

**Comment by perllb** [comment]
Great, seems to work. Thanks.
