### ISSUE TITLE
Saving reads at the NanoporeBC_UMI_finder step

### ISSUE THREAD

**Issue by pchamely-2** [ucagenomix/sicelore#15]
Hi there, I'm working with some promeTHION data and I'm seeing some pretty huge losses in the number of reads where a BC and UMI are found. I wanted to play around with the --maxUMIfalseMatchPercent  and --maxBCfalseMatchPercent  options and was wondering what's the best route to go. Right now I have it set as the default:
--maxUMIfalseMatchPercent 2
--maxBCfalseMatchPercent 5

and I'm thinking of maybe just bumping each value up by one to try and save some more reads so that we have:
--maxUMIfalseMatchPercent 3 and 
--maxBCfalseMatchPercent 6 

Would love to hear your thoughts on whether or not this is a good idea, should I bump it up even further, are there other things I should try etc?

Here are some stats for reads lost along the way for my two datasets:
**One:**
Total # of Reads (Pre Processing): 45,297,706
Num of Reads with poly(A/T) and adapter sequences: 28,618,051 (63.2% of Total)
Num of Reads with illumina cell BC = 9,624,541 (21% of Total, 33.6% of reads with polyA)
Num of Reads with cell BC and UMIs found: 5,915,024 (13% of Total, 61% of reads with cellBC)
Final number of Valid sam records: 5,536,862 (12% of Total, 57% of reads with cellBC)

**Two:**
Total # of Reads (Pre Processing): 41,622,140
Num of Reads with poly(A/T) and adapter sequences: 25,715,068 (61.8% of Total)
Num of Reads with illumina cell BC = 6,631,329 (16% of Total, 26% of reads with polyA)
Num of Reads with cell BC and UMIs found:  2,290,587 (5.5% of Total, 34% of reads with cellBC)
Final number of Valid sam records: 2,112,296 (5.1% of Total)

Please do let me know if there is any other info that I could provide that would be helpful!

Thanks,
Paulina

**Comment by RainerWaldmann** [comment]
Hi Paulina,
I coded the NanoporeBC_UMI_finder. 
The fraction of BCs found (33.6% of reads with polyA) is really very low. Should be far above 50% (typically 60 - 70%) with the current Nanopore read quality and the default parameters. 

- How were the Nanopore read qualities for those runs (run reports) ? 
- Could you email me (waldmann@ipmc.cnrs.fr) the config.xml. Just to make sure that there are no issues there.
- I would also need some info on the stats for the Illumina data from the Cellranger report (e.g. fraction of reads in cells) for troubleshooting.

With just about 60% the fraction of reads that have a polyA/adapter is rather low. In the 10xGenomics PCR  product there are quite a lot of PCR byproducts that don't have a polyA and adapter. While those are lost in the Illumina library preparation workflow, they end up in the Nanopore libraries. To reduce the fraction of those useless reads just do the biotin selection (optional step in our published protocol) for any future libraries.

Rainer

**Comment by pchamely-2** [comment]
Hey Rainer - just send an email with all the info.

Thanks!
Paulina
