### ISSUE TITLE
UMIs assigned without matched gene

### ISSUE THREAD

**Issue by uni-hd** [ucagenomix/sicelore#16]
Hello Sicelore developers, 

I am led here following your paper: https://www.nature.com/articles/s41467-020-17800-6. I downloaded GSE130708 and ran Sicelore on the 190c dataset. I found 37% of the assigned UMIs are not associated with a gene. Are they reliable? How can I force the tool to search UMIs requiring Nanopore and Illumina matched for the same gene rather than for the same genomic region? Thanks!

**Comment by RainerWaldmann** [comment]
The following cases are possible where a BC/UMI is not found in Illumina data for the same genomic region but not for the same gene:
1)	The short Illumina read is either intronic or slightly 3’ of the annotated gene. CellRanger won’t assign this read to a gene.
2)	 Most of the short Illumina reads are in 3’ UTRs. Repeats or other low complexity sequences might lead to mapping ambiguities. I have more confidence in the gene assigned to a long Nanopore read than to a short Illumina read from the 3’ UTR. I would rather use the Nanopore gene.
3)	Reads corresponding to non-annotated transcripts obviously won’t have any associated gene.

UMIs found for a genomic region are reliable. BCs and UMIs have to be found for the same genomic region within a narrow window of 500 nt (default, or the value provided [-w parameter] during Illumina parsing) for both Illumina and Nanopore data. This is even more stringent than finding a BC/UMI just for the same gene.

If you want to identify only UMIs that are found for the same gene you can either set the flag for genomic region search in the config.xml to false (<test_BC_Genomic_Regions>**false**</test_BC_Genomic_Regions>) 
or select for SAM entries with the BD tag set (indicates BC and UMI found for a gene in the short read data).
Config.xml
          <FOUND_FOR_ILLUMINA_CELL_GENE>
                <samFlag>**BD**</samFlag>
                <description>Cell BC found for matching Illumina Cell BC for data for same gene in same cell</description>
            </FOUND_FOR_ILLUMINA_CELL_GENE>

Rainer

**Comment by uni-hd** [comment]
thanks!
