### ISSUE TITLE
the SNP file  of  SNPMatrix

### ISSUE THREAD

**Issue by crystal0721** [ucagenomix/sicelore#17]
Dear,
   Thanks for the tools of  SiCeLoRe,while we  had test the softwore of  SiCeLoRe.  In the step10( SNPMatrix),there is need SNP file， so we want to know how to get this file. Hope your apply and thanks very much.

**Comment by ucagenomix** [comment]
Please have a look at Sicelore README for SNP file format:
https://github.com/ucagenomix/sicelore#snp-calling

**Comment by crystal0721** [comment]
Thanks for your reply. we had  seen the SNP file format. While we want to know how to obtain the SNP  file. From the Sicelore README, the SNP file should be prepared  before Sicelore, should we call SNP by GATK？

**Comment by ucagenomix** [comment]
Hi,
You actually need to provide the list of the SNVs you want to explore and quantify, 
GATK might be a solution, i've used longshot for ONT reads (https://github.com/pjedge/longshot).
