### ISSUE TITLE
the results of IsoformMatrix

### ISSUE THREAD

**Issue by crystal0721** [ucagenomix/sicelore#18]
Hi,  We have  same questions about the isomatrix.txt  obtained by IsoformMatrix,  why  the transcriptId of same genes is 'undef', how to understand it and  should those transcriptIds could be used to  single-cell clustering analysis.  Thanks.

**Comment by ucagenomix** [comment]
Hi, 
There might be a lot of truncated molecules (between 30% to 50% depending on library prep.) that can be assigned to a geneId but can not be assigned to a specific transcriptId (require exact exon/exon structure compared to the refflat reference file in STRICT mode), those molecules are listed as "undef" in the isoform matrix and must be removed for further analysis at the isoform level. In case you get too many truncated molecules in your library prep. you can also work with the junction matrix.
