### ISSUE TITLE
Getting the UMIs for the reads in the SNPmatrix

### ISSUE THREAD

**Issue by pchamely-2** [ucagenomix/sicelore#2]
Hi there, I'm also working on the project with @gm-nyc and we want to do a genotyping comparison between our Illumina and Nanopore reads at a CB+UMI : CB+UMI basis instead of just a cell: cell basis. So I'm wondering if there is a way to get the actual UMI's associated with the reads that were accounted for in the SNPmatrix. If we have the UMI's, we will be able to pull the actual reads with/without the SNP, from the consensus file, since we already have the CBs

**Comment by ucagenomix** [comment]
Donwload Sicelore.jar latest build from today integrating a new output file (**$PREFIX_molinfos.txt**) for **SNPMatrix** pipeline where you can visualize SNP information on a per molecule basis (cellBC/UMI/nb_reads/SNPcall).

**Comment by pchamely-2** [comment]
Thank you so much...That worked perfectly!
