### ISSUE TITLE
the Gene count  compare the step2 with not through step2

### ISSUE THREAD

**Issue by crystal0721** [ucagenomix/sicelore#20]
hi，
  We used SiCeLoRe to analysis the single cell Nanopore  long read sequencing data. While  we found that  if we used the step2(Scan for poly(A) and adapters in Nanopore reads) or  not,  the Gene count obtained by IsoformMatrix  had vary  different, and  the  Gene count was lower used by the long reads which not used  step2 than the  reads that  got through  step2 passed, So we wonder the reason and would you help us，thanks very much.

**Comment by ucagenomix** [comment]
hello,
The pre-scanning step remove reads where a polyA is not found to avoid loosing time in the next steps, but also re-orient the reads to get the polyA and the barcodes at the end of the reads ("stranding the reads"). The reads are then stranded, you should see the difference looking at the bam files. The AddGeneNameTag requires strandness if USE_STRAND_INFO=true, if you do not pre-scan the reads and USE_STRAND_INFO=true, you might loose a lot of reads that wont be assigned a gene name and then lost during the IsoformMatrix step.
KL
