### ISSUE TITLE
the problem of  ExportClippedReads  

### ISSUE THREAD

**Issue by crystal0721** [ucagenomix/sicelore#22]
Hello,
    1、Thanks  for   the  software of sicelore. While when we used  ExportClippedReads  to analysis fusion. The  fastq  got for ExportClippedReads had no quality value,  the format of  fastq could be seen as follows:

@c2c65736-da35-47eb-bccc-0d8ed7d95f56_FWD_pA_Ad3p_TSO5p
ATATGCTTCGTTCAGTTACGTATTGCTCGCAAGCAGTGGTATCAACGCAAGAGTACATGGGAAGTATGTCTTCCTGGACCCCCTGGCTGGTGCTGTAACA
+
null
@52abbe09-34ec-46aa-99ad-e0444422f2a2_FWD_pA_Ad3p_TSO5p
AGTGACCCTTTCGTTCAGTTACGTATTGTAAAAGCAGTGGTATCAACGCAGAGTACATGGGGAGGGACAAGGCTGCTCTGTCCTGGTGCTCCCTGAAAAG
+
null

2、When  we used  those fastq from  ExportClippedReads to map (Minimap2 clipped reads mapping), we got the following error and  the empty file.
`Runtime.totalMemory()=1835008000
[M::mm_idx_gen::62.663*1.97] collected minimizers
[M::mm_idx_gen::70.768*3.47] sorted minimizers
[M::main::70.785*3.47] loaded/built the index for 194 target sequence(s)
[M::mm_mapopt_update::74.673*3.34] mid_occ = 765
[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 194
[M::mm_idx_stat::76.710*3.28] distinct minimizers: 167225302 (35.46% are singletons); average occurrences: 6.030; average spacing: 3.074
[WARNING] wrong FASTA/FASTQ record. Continue anyway.
[WARNING] wrong FASTA/FASTQ record. Continue anyway.`

3、So we  converted the fastq to fasta format and  used minimap2 to analysis.

**Comment by bumproo** [comment]
Hi,
I saw this same trouble. ExportClippedReads has quality strings of null and this causes an error in the minimap alignment of clipped fastq. It seems conversion to fasta for input to minimap might get around this but I'm not sure.

I think I tracked the issue down to the fact that a quality value tag is not being added to the bam file when I run the original

AddBamReadSequenceTag

the US is added but UQ is missing completely from the tags.
I tried both with Sicelore-1.0 and 2.0 and got the same result

Is this expected?

no trouble with t

**Comment by ucagenomix** [comment]
Hi, 
Sorry for the long delay, i really skipped this issue...
You are right charlie, the problem come from the AddBamReadSequenceTag pipeline, i deactivate once the UQ tag adding so ExportClippedReads is not able to export the QV values, i've just upload a dev version (Jar/dev_versions/Sicelore-2.001.jar) changing the behaviour of AddBamReadSequenceTag to add the QV values as UQ tag, should do the trick now but you need to rerun the AddBamReadSequenceTag to your cellBC/UMI assigned bam file input for ExportClippedReads.
best,

**Comment by bumproo** [comment]
Thanks a lot and no problem on the delay. I've tested the 2.001 jar and it works as expected.
Are those quality values considered in the SNPMatrix or FusionDetector steps?

It seems like SNPMatrix requires you to know a list of SNPs that you wish to assess in the ONT data, is that correct?

**Comment by ucagenomix** [comment]
Quality values are used for the SNPmatrix pipeline but not in the fusion detection one. QV are used to filter out low quality sequencing at SNV position to ensure high quality calling. Yes SNPmatrix requires a list of SNPs, we use it initialy for RNA A-to-I editing event quantification. You can easily perform a longshot SNV detection (https://github.com/pjedge/longshot) before feeding the list of detected SNVs to SNPmatrix. Note that you might have some systematic errors called as SNVs from nanopore reads in this list and need to be carefull. Next step could be to work on polymorphism and provide allele-specific-transcript-structure count matrices to work on ASTS projects.
