### ISSUE TITLE
refFlat file of current annotation

### ISSUE THREAD

**Issue by gy-chop** [ucagenomix/sicelore#23]
Hello,
Thanks for developing sicelore pipeline. When I try using the pipeline, I find 'refFlat.txt' file is required in several steps of sicelore. However, this file seems to be not available for current version of annotations (e.g. gencode vM25). How can I get a refFlat file of current version of annotation that can be used for the sicelore pipeline?

Best,

**Comment by ucagenomix** [comment]
hi,
Compatible refflat.txt file can be generated based on Gencode GTF file for genome build used 
for mapping with **gtfToGenePred** from UCSC.

$> gtfToGenePred -genePredExt -geneNameAsName2 gencode.vMxxx.primary_assembly.annotation.gtf gencode.vMxxx.primary_assembly.annotation.refflat.txt
$> paste <(cut -f 12 gencode.vMxxx.primary_assembly.annotation.refflat.txt) <(cut -f 1-10 gencode.vMxxx.primary_assembly.annotation.refflat.txt) > refFlat.txt
