### ISSUE TITLE
the analysis of  CollaspeModel 

### ISSUE THREAD

**Issue by crystal0721** [ucagenomix/sicelore#25]
Dear,
     When we analysis novel transcripts isoforms using  CollaspeModel,there are two files  need:cage_peaks.bed and polyAs.bed. Are they got from gtf  file?

**Comment by ucagenomix** [comment]
Hi,
please refer to README file, both files are bed file from Fantom and Gencode repositories : 
CAGE=CAGE peaks file (.bed) (Ressources/mm10.liftover.Fantom5.cage_peaks.bed)
POLYA=POLYA sites file (.bed) (Ressources/mm10.gencode.vM24.polyAs.bed)

you should find the same files for human if required.
best,
