### ISSUE TITLE
Scan for poly(A) adapter for 5' 10x sequence

### ISSUE THREAD

**Issue by AshDangerByrne** [ucagenomix/sicelore#27]
Hi,

I would like to use the NanoporeReadScanner.jar but this searches for the 3' Single Cell gene expression 10xGenomics adapter sequence "CTTCCGATCT." I am using the 5' Single Cell gene expression 10xGenomics method which has "GTACTCTGCGTTGATACCACTGCTT" adjacent to the poly-A sequence. It would be great if this was an option that the user can provide when scanning for the Nanopore reads. 

Thanks,
Ashley Byrne

**Comment by RainerWaldmann** [comment]
Hi Ashley,

I'll soon release a  new version of the software. Will also allow cell barcode / UMI assignment without Illumina data.  In this novel version  an option for 5' barcoding is already integrated.  We just need a 5' barcoded dataset to test it before we activate the 5' barcoding option.

Rainer

**Comment by AshDangerByrne** [comment]
Hi Rainer,

Thanks! I will also try out the Sicelorev2 and see if I have any issues.
Would you like to try using some of my 5' dataset to validate the pipeline?
Let me know.

Cheers,
Ashley Byrne

**Comment by yuukiiwa** [comment]
Hi Rainer,

I am very interested in using the version of `sicelore` with a 5' barcoding option. I saw that the latest commit says `v1.0` but there is a file called `quickrun.v2.sh` in the directory. I wonder whether the 5' barcoding option is already publicly available? If not, around when will it be available?
Thank you!!

Best wishes,
Yuk Kei

**Comment by amitblum** [comment]
Hello Rainer,
Do you have news regarding the newest version of SiCelore? 

Thanks
Amit

**Comment by yuchen345** [comment]
Hello, @AshDangerByrne ,
Have you solved your 5' dataset problem with SiCelore or any other pipelines?
Hoping for your reply!
Thanks
Yuchen

**Comment by ucagenomix** [comment]
Please visit Sicelore-2.1 github repository for this issue:
[https://github.com/ucagenomix/sicelore-2.1](https://github.com/ucagenomix/sicelore-2.1)
