### ISSUE TITLE
Low rates of UMI assignment

### ISSUE THREAD

**Issue by bumproo** [ucagenomix/sicelore#28]
Hi,

I am working on troubleshooting low rates of UMI assignment at the NanoporeBC_UMI_finder-1.0.jar step with several different 10x/ONT datasets. I see between 1%-5% of my passed reads from NanoporeReadScanner-0.5.jar and initial minimap alignment output reported in my x__GEUS10xAttributes_umifound_.bam result.

As part of this work, I have worked though your example dataset:
190c.clta.illumina.bam
cellBC.190.tsv
190c.clta.nanopore.reads.fq

using my own mm10 genome with ensembl v101 data (mm10_ens101_junc.bed, mm10_ens101.refFlat) and my own environment. In this test run, I get 10147 passed fastq sequence.
10144 of these are reported in the minimap and _GEUS10xAttributes.bam alignment files.
3919 are in the GEUS10xAttributes_umifound_.bam alignment file.
the log data from NanoporeBC_UMI_finder-1.0.jar is below.

The 40% UMI assignment rate is much better than I am doing with my own data but I also wonder if these test data numbers are consistent with your results?
Thanks,
Charlie

------------ S T A T S  F 0 R  R E A D S --------------------------
Number of reads 10,144
Reads with Gene 10,058 (99.2 %)
--DIVERS--
Number of reads:        10,144 (100 %)
Read too short: 0 (0 % of total)
No matching gene found in Illumina:     140 (1.4 % of total)
Genomic region not found in Illumina:   58 (0.6 % of total)
--POLY AT--
No poly A nor poly T found:     0 (0 % of total)
Poly A or poly T found at one end:      10,119 (99.8 % of total)
Poly A or poly T found at both ends:    25 (0.2 % of total)
Pre poly AT too short:  3 (0 % of total)
--TSO--
TSO one end, adapter other end: 9,590 (94.5 % of total)
TSO one end, no adapter:        0 (0 % of total)
TSO at both ends:       0 (0 % of total)
--ADAPTER--
Adapter found at one end:       10,135 (99.9 % of polyAT at one end)
Adapter found one end read with gene:   10,050 (99.3 % of polyAT at one end)
Adapter found at both ends:     25 (0.2 % of total)
--CELL BARCODES--
Corresponding Illumina cell BC for gene found:  6,615 (65.3 % of reads with correct adapter)
Corresponding Illumina cell BC for genomic region found:        67 (0.7 % of reads with correct adapter)
BC only found in empty drops:   733 (7.3 % of reads with gene and correct adapter)
BC only found in all 10x selected cells:        81 (0.8 % of reads with gene and correct adapter)
-- UMI --
UMI found:      3,919 (58.7 % of reads with Illumina cell BC found)
UMI for genes found:    3,854 (58.3 % of reads with Illumina gene BC found)
UMI for genomic region found:   65 (97 % of reads with Illumina genomic region  BC found)
--INTERNAL POLY_AT / ADAPTERS--
Read has internal poly A or T:  1,495 (14.7 % of total)
Read has internal poly A or T and adapter:      83 (0.8 % of total)

**Comment by ucagenomix** [comment]
Hi,
Yes our subset is representative of our dataset, this is an extract of the Clta region fom our 190 cells dataset.
Observing a low BC/UMI assignment rate is related to a too low Illumina sequencing depth,
what is your sequencing saturation ? A futur version of the pipeline will adress that kind of issue using
illumina independant assignation directly from nanopore reads.
best,

**Comment by bumproo** [comment]
Hi, 
Thanks for the reply. Does my rate of UMI assignment in the Clta test match up with what you would expect for the data?

I've been focusing on one 10x run that has associated ONT and PacBio data. The 10x sequencing is quite deep. roughly 2500 cells, 160,000 reads per cell, 2000 genes per cells. The pacbio run for this 10x library produced 702,000 reads in the sicelor Scan passed set and 6% of these get UMI assigned by sicelor. The ONT run produced 4.8 million passed reads, 4.2% get UMI assignment.

I've been doing a deep dive into the ACTB locus. For PacBio, I see 285/3844 ACTB reads with UMI assignment. For ONT the fraction is 451/10651 ACTB reads with UMI assignment. Regarding the 10x, there are 505,000 reads with cell barcode and UMI assigned to this locus. Potential problems I may be having are that the 10x cell barcodes all have a suffix "-1" and the UMI in the UB field range from 2-12 with about 70% length 12. This iteration of my sicelor run set UMI to 10. I've experimented with this already but will do some more work.

I've also extracted ACTB pacbio and ont reads with and without UMI assignments and done clustalx alignments. In almost all cases, the TSO and 3' adapters are obvious, as are the cell barcodes. I have not yet been able to figure out why some UMI are assigned and others are not.

A specific question about sicelore/Jar/Sicelore-1.0.jar IsoformMatrix... Can you explain the difference between "SAMrecords valid" and "SAMrecords unvalid"? my unvalid counts are very high

Thanks!
Charlie

**Comment by bumproo** [comment]
I have replaced my hand edited umiMaxEditDistances.xml file with:
https://raw.githubusercontent.com/ucagenomix/sicelore/master/Jar/umiMaxEditDistances.xml
that specifies the 12nt UMI.

I am still only seeing <2% of sam records with UMI in a new NanoporeBC_UMI_finder-1.0.jar run.

**Comment by ucagenomix** [comment]
The Clta rate is what we expect from our subset.
What is the sequencing saturation given in the web_summary.html report from cellranger analyis ? i suspect 160k reads per cell should give a high sequencing saturation.
Yes <2% cellBC/UMI asignment is really low and obviously not really satifying, could you copy.paste the log file from assignement. Note that the UMI should be in the U8 tag the UB is the uncorrected sequence.
During IsformMatrix pipeline we remove SAMrecords that dont have cellBC/UMI and a gene name tag, we remove also records considered as chimeric (i.e. > 150nt hard/soft cliping, can be changed) and having a mapqv=0 (you can keep them with MAPQV0=true). What is the different categories of unvalid records for your dataset ?





thats also why you have an important number of unvalid count at the en

**Comment by bumproo** [comment]
Thank you very much for the help with this.
The sequencing saturation according to cellranger web summary is 65.1%

for the U8 vs UB, I don't see the tag U8 in my cellrager possorted bam file but it looks like the UMI is stored in UB
for the sicelore bam files, umi is in U8

I'm working on the log file and different categories of unvalid.

**Comment by bumproo** [comment]
My problems are being caused by 10x sequencing saturation. I have another dataset with 96% saturation and 73% UMI assignment. Thank you very much for your help with this, I am going to avoid low-saturation 10x runs going forward.
