### ISSUE TITLE
Errors when using IlluminaParser.jar

### ISSUE THREAD

**Issue by alicecsq** [ucagenomix/sicelore#31]
Hi, I have some issues running IlluminaParser.jar.

I used spaceranger, following the instructions (see image), to generate the Illumina bam file, which did not include --geneFlag (GN). 
<img width="761" alt="Screenshot 2021-04-17 at 12 04 35 PM" src="https://user-images.githubusercontent.com/51415436/115119234-4f93ac00-9f75-11eb-970b-a888fea272b4.png">

here is a few line of the output BAM file from 10x spaceranger
A00984:319:HT72MDSXY:4:1338:32416:31923	16	GRCh38_chr1	14503	0	90M	*	0	CAGGCAGACAGAAGTCCCCGCCCCAGCTGTGTGGCCTCAAGCCAGCCTTCCGCTCCTTGAAGCTGGTCTCCACACAGTGCTGGTTCCGTC	FFFFFFFFF:FFFFFFFFF:FFFFFFFFF:FFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF	NH:i:6	HI:i:1	AS:i:88	nM:i:0	RG:Z:1k_hgmm_3p_LT:0:1:HT72MDSXY:4	RE:A:I	xf:i:0	CR:Z:AGTAGTCAGTCATCCA	CY:Z:FFFFFFFFFFF:FFFF	CB:Z:AGTAGTCAGTCATCCA-1	UR:Z:AGCTACTGAGCT	UY:Z:F:FFFFFFFFFF	UB:Z:AGCTACTGAGCT

I run the IlluminaParser-1.0.jar with the '190c.clta.illumina.bam' and it worked. I think it is because I am missing the GN tag.
**How do I include GN/GX in the BAM output from 10x spaceranger?** 

Then I run IlluminaParser-1.0.jar with 
`java -Xmx15000m -jar ~/software/sicelore/Jar/IlluminaParser-1.0.jar --inFileIllumina possorted_genome_bam.bam --tsv filtered_feature_bc_matrix/barcodes.tsv.gz --outFile illuminaParsed.bam.obj --cellBCflag CB --umiFlag UB --geneFlag GN`
and **got the following error**:

+++++++   ILLUMINAPARSER 1.002_2Build Feb. 20, 2020++++++++++++
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 65533 out of bounds for length 254
	at com.rw.nuc.encoding.TwoBit.NucleicAcidTwoBitPerBase.getLongHashForSeq(NucleicAcidTwoBitPerBase.java:156)
	at com.rw.nuc.encoding.TwoBit.NucleicAcidTwoBitPerBase.<init>(NucleicAcidTwoBitPerBase.java:412)
	at com.rw.bamparsermaven.Parser.getCellsToUseFromCellRangerTSV(Parser.java:261)
	at com.rw.bamparsermaven.Parser.parse(Parser.java:141)
	at com.rw.bamparsermaven.Main.main(Main.java:99)

**Why do I get this error?**

I then attempted 'IlluminaParser-1.002.jar'
`java -Xmx15000m -jar ~/software/sicelore/Jar/IlluminaParser-1.002.jar --inFileIllumina possorted_genome_bam.bam --tsv filtered_feature_bc_matrix/barcodes.tsv.gz --outFile illuminaParsed.bam.obj --cellBCflag CB --umiFlag UB --geneFlag GN`
and **got the following error** 
+++++++   ILLUMINAPARSER 1.002_2  Build Feb. 20, 2019++++++++++++
****************************************************************************************************************************************
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  EXPIRED 2020-06-06 - Download a new version from Github !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
****************************************************************************************************************************************

I just cloned the directory two days ago. I am not sure if re-cloning the GitHub page would help (as suggested in closed 'issues' session).

Could you help me with this issue? 
Thank you!

**Comment by RainerWaldmann** [comment]
Hi,

The version that gives you an expiry error is an old version. The current version does not expire.
You supplied the barcodes.tsv.gz file. The version on Github does not support compressed barcode lists. Just uncompress it and supply the tsv. This should fix the problem.

Rainer

**Comment by alicecsq** [comment]
Hi Ranier,
        It worked now. Thank you so much!!

Best,
Alice
