### ISSUE TITLE
Ignoring SAM validation error when runing IlluminaParser-1.0.jar

### ISSUE THREAD

**Issue by yangao07** [ucagenomix/sicelore#32]
Hi,

I downloaded the 190 cells Illumina datasets SRR9008424.bam from SRA.
While running IlluminaParser-1.0.jar to generate the .bam.obj, I got many error message like this:
`Ignoring SAM validation error: ERROR: Record 7, Read name 1, RG ID on SAMRecord not found in header: TGCGGCTT
Ignoring SAM validation error: ERROR: Record 8, Read name 2, RG ID on SAMRecord not found in header: GATTCTGG
Ignoring SAM validation error: ERROR: Record 9, Read name 3, RG ID on SAMRecord not found in header: GATTCTGG
Ignoring SAM validation error: ERROR: Record 11, Read name 4, RG ID on SAMRecord not found in header: CCACTACC
Ignoring SAM validation error: ERROR: Record 12, Read name 5, RG ID on SAMRecord not found in header: CCACTACA
Ignoring SAM validation error: ERROR: Record 13, Read name 6, RG ID on SAMRecord not found in header: GTTTCTGG
Ignoring SAM validation error: ERROR: Record 22, Read name 7, RG ID on SAMRecord not found in header: TGCGGCTT
Ignoring SAM validation error: ERROR: Record 23, Read name 8, RG ID on SAMRecord not found in header: ATGAAGAC
Ignoring SAM validation error: ERROR: Record 29, Read name 9, RG ID on SAMRecord not found in header: CCCCTACA
Ignoring SAM validation error: ERROR: Record 35, Read name 10, RG ID on SAMRecord not found in header: CCACTACA`

However, the program can still finish. 
My question is does this error affect the final result?

Thanks!
Yan

**Comment by ucagenomix** [comment]
Hi,
It seems to be an error coming from the Read Group and related to how SRA stores our uploaded bam file.
DId you export the bam file from SRA, might be better to export the fastq reads directly.
But the fact that there is only one sample in the bam and so no read group needed might indicate that those warnings are not changing the final result but i can not be 100% sure.
best,
kevin

**Comment by yangao07** [comment]
Hi Kevin,

I re-downloaded the original `190c_possorted_genome_bam.bam` from SRA using `wget`, there are no errors anymore.

Thanks for the reply.

Yan

**Comment by yangao07** [comment]
Hi Kevin, 

A follow-up question about the nanopore long-read data in your NC paper.
It was mentioned that 30M and 332M reads were generated for the 190 and 951 cells. 
However, from the NCBI website, I can only download ~9M and ~47M.
(https://www.ncbi.nlm.nih.gov/sra/?term=SRR9008425, https://www.ncbi.nlm.nih.gov/sra/?term=SRR9008427)

Are those data from NCBI filtered?

Thanks!
Yan

**Comment by ucagenomix** [comment]
Hi Yan,
yes GEO required us to upload the reads that were cell barcode assigned so this is the set of reads after the whole assignment workflow.
best,
kevin

**Comment by yangao07** [comment]
OK, I see.
Thanks!

**Comment by yangao07** [comment]
Another question (forgive my bothering:)), 
when you do base-calling on fast5 files, did you use guppy and in high-accuracy mode?
