### ISSUE TITLE
null sequence and quality in consensus sequence

### ISSUE THREAD

**Issue by defendant602** [ucagenomix/sicelore#39]
Sorry to bother you. When I run "compute consensus sequence" in quickrun.v2.sh, I have found quite a lot of null sequence in the ouput consensus.fq, and for the molecures which have normal sequence, all the quality value in the quality line are "$" symbol. I want to know if it is normal for this step?

The consensus.fq looks like this:
![image](https://user-images.githubusercontent.com/37471184/123531409-db287680-d736-11eb-9299-831afbf463b1.png)

My version of spoa and racon is v3.0.2 and v1.3.3, respectively.

Thnaks!

**Comment by defendant602** [comment]
and in the stderr of "compute consensus sequence" step, I got many exceptions of "java.lang.NullPointerException".

```
java.lang.NullPointerException
        at org.ipmc.sicelore.utils.ConsensusMsa.process(ConsensusMsa.java:51)
        at org.ipmc.sicelore.utils.ConsensusMsa.<init>(ConsensusMsa.java:40)
        at org.ipmc.sicelore.utils.Consensus.call(Consensus.java:225)
        at org.ipmc.sicelore.utils.Consensus.call(Consensus.java:14)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by ucagenomix** [comment]
Hi,
consensus sequence is computed when you got at least 3 reads per UMI. The null values obtained when you have >2 reads per UMI mean that spoa is not working properly, you should look at the tmp directory rights permission and the spoa output files from cmd line 'spoa -r 2 /tmp/molecule_reads.fa > /tmp/molecule.msa'
You can set DEBUG=true to keep tmp files to debug whats not going well in your environnement.

best,

**Comment by defendant602** [comment]
Hi, Thanks for your reply!  The cmd "spoa -r 2 /tmp/molecule_reads.fa > /tmp/molecule.msa" work just fine, no error message occurred. The ouput msa file looks like this:

![image](https://user-images.githubusercontent.com/37471184/123765559-6d2bad00-d8f8-11eb-80ec-5f8c1afe533c.png)

Should I try the jar files in the dev_versions directory?

**Comment by ucagenomix** [comment]
Are you sure to submit the jar file with a valid TMPDIR, that exists and where you have read/write permissions ?
You can try the jar files in the dev version, but it should not change this error.
