### ISSUE TITLE
Failure to generate GEUS10xAttributes.bam

### ISSUE THREAD

**Issue by liuzj039** [ucagenomix/sicelore#4]
Hello,
I encountered some unexpected situations when I executed this command located in the quickrun.sh script.

`java -jar -Xmx4g Jar/NanoporeBC_UMI_finder-1.0.jar -i $output_dir/GEUS.bam -o $output_dir/GEUS10xAttributes.bam -k $output_dir/190c.clta.illumina.bam.obj --maxUMIfalseMatchPercent 1 --maxBCfalseMatchPercent 5 --logFile $output_dir/out.log`

After the command runs, the screen outputs “ ***** will generate 40threads”. But after I waited for a day, it still only just generated two empty file.

Could you give me some suggestion about how to run this command successfully?
Thanks,
Zhijian

**Comment by ucagenomix** [comment]
This error occurred when using 40 cpus on the small test dataset.
Please try it again with today’s build, it should now works wih "--ncpu 8" parameter.

**Comment by liuzj039** [comment]
It worked!!! Thank you so much!!!!!
