### ISSUE TITLE
how to get junctions.bed  

### ISSUE THREAD

**Issue by markme123** [ucagenomix/sicelore#40]
hello,   which can i chose quickrun.sh or quickrun.v2.sh;  
how to get gencode.v31.hg38.junctions.bed and gencode.v31.hg38.refFlat.txt
What is the data loss rate of this pipline

**Comment by EduardoGCCM** [comment]
Hi,
I don't know if this is still useful for you. These are the commands I have used.

For gBED generation:
 `minimap2 -d human.mmi Gencode_v39/fasta/gencode_v39.fa                     # indexing
paftools.js gff2bed -j Gencode_v39/gtf/gencode_v39_primary.gtf > human.bed`

For refFlat:
`gtfToGenePred -genePredExt -geneNameAsName2 Gencode_v39/gtf/gencode_v39_primary.gtf human.refflat.txt
paste <(cut -f 12 human.refflat.txt) <(cut -f 1-10 human.refflat.txt) > refflat.txt`

Best,
Eduardo
