### ISSUE TITLE
how to make SCORE method work?

### ISSUE THREAD

**Issue by icanccwhite** [ucagenomix/sicelore#49]
[Thu Aug 19 14:15:22 CEST 2021] IsoformMatrix INPUT=GEUS10xAttributes_umifound_.bam REFFLAT=refFlat.txt CSV=barcodes_rm.tsv DELTA=2 OUTDIR=step2.tmp PREFIX=sicelore ISOBAM=false METHOD=SCORE CELLTAG=BC UMITAG=U8 GENETAG=GE MAXCLIP=150 AMBIGUOUS_ASSIGN=true    TSOENDTAG=TE UMIENDTAG=UE POLYAENDTAG=PE USTAG=US RNTAG=RN MAPQV0=false VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Thu Aug 19 14:15:22 CEST 2021] Executing as user@node on Linux 3.10.0-1160.15.2.el7.x86_64 amd64; OpenJDK 64-Bit Server VM 1.8.0_282-b08; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: null
INFO    2021-08-19 14:15:22     IsoformMatrix           Cells detected          [18641]
INFO    2021-08-19 14:15:22     IsoformMatrix           Isoform method: [SCORE] not allowed, only STRICT method allowed (SCORE disabled)
[Thu Aug 19 14:15:22 CEST 2021] org.ipmc.sicelore.programs.IsoformMatrix done. Elapsed time: 0.00 minutes.
Runtime.totalMemory()=2075918336

**Comment by ilead-cong** [comment]
Hi， I met the same error with your statement. So have you resolved this problem? @icanccwhite
