### ISSUE TITLE
external bam file of Novel transcripts isoforms detection 

### ISSUE THREAD

**Issue by icanccwhite** [ucagenomix/sicelore#50]
Is there a dataset that confirmed in an external short read data given as STAR aligned bam file by at least juncCo reads?  
I picked one fqs of PRJNA286233 and aligned it with STAR, but the result was nothing. 

[Mon Sep 13 11:24:30 CEST 2021] CollapseModel INPUT=sicmol_isobam.bam REFFLAT=Gencode/gencode.v18.mm10.refFlat.txt CSV=Barcodes/cellBC.190.tsv DELTA=2 MINEVIDENCE=5 RNMIN=1 OUTDIR=output_dir/tmp PREFIX=CollapseModel SHORT=Aligned.sortedByCoord.out.bam CAGE=Ressources/mm10.liftover.Fantom5.cage_peaks.bed POLYA=Ressources/mm10.gencode.vM24.polyAs.bed    CELLTAG=BC UMITAG=U8 GENETAG=IG ISOFORMTAG=IT RNTAG=RN TMPDIR=/share/data/scratch/sicelore/ NTHREADS=20 MAXUMIS=20 MINPS=3 MAXPS=20 DEBUG=false CAGECO=50 POLYACO=50 JUNCCO=1 VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Mon Sep 13 11:24:30 CEST 2021] Executing as ... on Linux 3.10.0-1160.15.2.el7.x86_64 amd64; OpenJDK 64-Bit Server VM 1.8.0_282-b08; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: null
INFO    2021-09-13 11:24:30     CollapseModel           Cells detected          [190]
INFO    2021-09-13 11:24:30     UCSCRefFlatParser       UCSCRefFlatParser       start...
INFO    2021-09-13 11:24:32     UCSCRefFlatParser       UCSCRefFlatParser       end...
INFO    2021-09-13 11:24:32     UCSCRefFlatParser       Number of Genes Symbols [54166]
INFO    2021-09-13 11:24:32     UCSCRefFlatParser       Number of Transcripts   [136630]
INFO    2021-09-13 11:24:32     UCSCRefFlatParser       Loader Bam Start...
org.ipmc.sicelore.utils.LongreadParseException: Invalid Bam file. AAGGAGCAGTATTGGA-AGAAGTCTAT-7, Can't parse: 
        at org.ipmc.sicelore.utils.LongreadRecord.fromSAMRecord(LongreadRecord.java:253)
        at org.ipmc.sicelore.utils.UCSCRefFlatParser.loader(UCSCRefFlatParser.java:161)
        at org.ipmc.sicelore.programs.CollapseModel.process(CollapseModel.java:147)
        at org.ipmc.sicelore.programs.CollapseModel.doWork(CollapseModel.java:123)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:277)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
        at org.ipmc.sicelore.cmdline.SiCeLoReMain.main(SiCeLoReMain.java:40)
Caused by: java.lang.NullPointerException
        at org.ipmc.sicelore.utils.LongreadRecord.fromSAMRecord(LongreadRecord.java:162)
        ... 6 more
INFO    2021-09-13 11:24:32     UCSCRefFlatParser       Collapser Start...[0 total genes]
INFO    2021-09-13 11:24:32     CollapseModel           Perform validation using provided CAGE bed, POLYA bed and SHORT read bam files
INFO    2021-09-13 11:24:34     UCSCRefFlatParser       BEDParser       Ressources/mm10.liftover.Fantom5.cage_peaks.bed [references=22,entries=158954]
INFO    2021-09-13 11:24:34     UCSCRefFlatParser       BEDParser       Ressources/mm10.gencode.vM24.polyAs.bed [references=21,entries=27170]
INFO    2021-09-13 11:24:34     UCSCRefFlatParser       Validator Start...[0 total genes]
INFO    2021-09-13 11:24:34     UCSCRefFlatParser       Printing statistics...
INFO    2021-09-13 11:24:34     UCSCRefFlatParser       -----------------------------------------------------------------------
INFO    2021-09-13 11:24:34     UCSCRefFlatParser                                               all_set (UMI)   valid_set (UMI)
INFO    2021-09-13 11:24:34     UCSCRefFlatParser       total_genes                             0
INFO    2021-09-13 11:24:34     UCSCRefFlatParser       total_isoforms                          0 (0)   0 (0)
INFO    2021-09-13 11:24:34     UCSCRefFlatParser       full_splice_match
INFO    2021-09-13 11:24:34     UCSCRefFlatParser        o gencode                              0 (0)   0 (0)
INFO    2021-09-13 11:24:34     UCSCRefFlatParser       novel_in_catalog
INFO    2021-09-13 11:24:34     UCSCRefFlatParser        o combination_of_known_junctions       0 (0)   0 (0)
INFO    2021-09-13 11:24:34     UCSCRefFlatParser        o combination_of_known_splicesites     0 (0)   0 (0)
INFO    2021-09-13 11:24:34     UCSCRefFlatParser       novel_not_in_catalog
INFO    2021-09-13 11:24:34     UCSCRefFlatParser        o at_least_one_novel_splicesite        0 (0)   0 (0)
INFO    2021-09-13 11:24:34     UCSCRefFlatParser       ------------------------------------------------------------------------
INFO    2021-09-13 11:24:34     CollapseModel           Exporting all isoforms consensus sequence to fasta...
INFO    2021-09-13 11:24:34     UCSCRefFlatParser       Calling consensus start with 20 threads
INFO    2021-09-13 11:24:34     UCSCRefFlatParser       Total consensus to compute      0
[Mon Sep 13 11:24:34 CEST 2021] org.ipmc.sicelore.programs.CollapseModel done. Elapsed time: 0.07 minutes.
Runtime.totalMemory()=2075918336

**Comment by chenghuihui2018** [comment]
Hi， I met the same error with your statement. So have you resolved this problem? @icanccwhite

**Comment by albyrne0815** [comment]
Hi, I also had the same issue. How was this resolved @icanccwhite  
With "org.ipmc.sicelore.utils.LongreadParseException: Invalid Bam file. AAGGAGCAGTATTGGA-AGAAGTCTAT-7, Can't parse:"
