### ISSUE TITLE
*.molinfos.txt output file

### ISSUE THREAD

**Issue by amitblum** [ucagenomix/sicelore#54]
Hi
Could you please explain the meaning of the output *.molinfos.txt? What does each column represent? especially the following columns: nbReads ,nbSupportingReads , mappingPctId .

Thanks
Amit

**Comment by ucagenomix** [comment]
Hi, 

molinfos.txt present usefull informatons about the UMIs processed within the IsoformMatrix pipeline. Note that isoformMatrix can be run on a molecules bam file, ie. after consensus sequence calling for each UMI, or directly on the reads bam file.

nbReads = number of reads carrying the UMI (not usefull in case of molecule bam file)
nbSupportingReads = number of those reads that have the exact exonic structure of the reference isoform assigned (not usefull in case of molecule bam file)
mappingPctId =%age of identity versus genome reference, use it to plot the mapping %age according to the number of reads per UMI to see increase of sequence accuracy with number of reads per UMI (if your long-read sequencing depth is high)

best,
kevin

**Comment by amitblum** [comment]
Thanks for the information.
Amit
