### ISSUE TITLE
SNPMatrix - "nothing has been detected, check your input parameters ..."

### ISSUE THREAD

**Issue by KokoroO7** [ucagenomix/sicelore#57]
Hi, thank you for your splendid sicelore.
I struck with an error that I cannot solve.
I used demodata and quickrun.v2.sh, and then tested SNPMatrix, but had an error such that
(I tried using my own data and got the same error).
Is this error derived from data itself ? or wrong parameters ?
I appreciate for your help.
-------------------------------------------

********** NOTE: Picard's command line syntax is changing.
**********
********** For more information, please see:
********** https://github.com/broadinstitute/picard/wiki/Command-Line-Syntax-Transition-For-Users-(Pre-Transition)
**********
********** The command line looks like this in the new syntax:
**********
**********    SNPMatrix -I /path-to-sicelore/sicelore/output_dir_v2/molecule.tags.GE.bam -MINRN 0 -CELLTAG BC -UMITAG U8 -RNTAG RN -CSV /path-to-sicelore/sicelore/Barcodes/cellBC.951.tsv -SNP /path-to-sicelore/sicelore/Data/snp_description.csv -O /path-to-sicelore/sicelore/output_dir_v2/snpcall_output// -PREFIX snp
**********

[Tue Jan 04 16:38:49 xxx 2022] SNPMatrix INPUT=/path-to-sicelore/sicelore/output_dir_v2/molecule.tags.GE.bam CSV=/path-to-sicelore/sicelore/Barcodes/cellBC.951.tsv SNP=/path-to-sicelore/sicelore/Data/snp_description.csv OUTPUT=/path-to-sicelore/sicelore/output_dir_v2/snpcall_output PREFIX=snp CELLTAG=BC UMITAG=U8 RNTAG=RN MINRN=0    MINQV=0 VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Tue Jan 04 16:38:49 xxx 2022] Executing as xxxxx@xxxxx-System-Product-Name on Linux 5.4.0-72-generic amd64; OpenJDK 64-Bit Server VM 1.8.0_152-release-1056-b12; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: null
INFO    2022-01-04 16:38:49     SNPMatrix       Cells detected          [951]
INFO    2022-01-04 16:38:49     SNPMatrix       end of processing...    nothing has been detected, check your input parameters (if Illumina set CELLBC=CB UMITAG=UB), no output files generated
INFO    2022-01-04 16:38:49     SNPMatrix       STATISTICS...           hits=0, lowRN=0, lowQV= 0
[Tue Jan 04 16:38:49 xxx 2022] org.ipmc.sicelore.programs.SNPMatrix done. Elapsed time: 0.00 minutes.
Runtime.totalMemory()=2058354688

**Comment by ucagenomix** [comment]
hi,
sorry for the delay,
the small dataset we provide for testing does not include a polymorphism which can be called using SNPmatrix pipeline, so that is normal having nothing in the output. Concerning your data, are you sure to visualize a SNP at the position you provide in the description file ? using MINRN=0 MINQV=0 should intergate din the analysis all the UMI in the molecule bam file you provide.
tell me in you need more help,
best,
kevin

**Comment by SergiuPasca** [comment]
Hi,
I have the same error message using the bam output from (https://github.com/epi2me-labs/wf-single-cell). Tried MINRN=0 MINQV=0; also tried CB, CB:Z: and CR as an argument for CELLBC. Also tried using the cell barcodes file both with or without "-1". I get the same error message regardless of the approaches mentioned above. Is there something else I could try? I do not have the RN tag in the bam, could this be an issue?
Best,
Sergiu
