### ISSUE TITLE
How to build Sicelore-2.0.jar? pom.xml shows version as 1.0-SNAPSHOT

### ISSUE THREAD

**Issue by mxvanzant** [ucagenomix/sicelore#58]
Hi, I don't see how to build Sicelore-2.0.jar from source. Your pom.xml file shows version as 1.0-SNAPSHOT. Am I missing something?
Thank you,
Mike

**Comment by ucagenomix** [comment]
hi,
not sure to publish all you need to do it easily, 
i'm working within a netbean project if this can helps.
best,
kevin

**Comment by mxvanzant** [comment]
Hi Kevin,
Let me clarify my question: I am looking for the Sicelore-2.0 source code and I am not sure if the 2.0 source is in this repository or somewhere else. Is the source code at github.com/ucagenomix/sicelore actualy version 2.0 code? It is confusing to me that the pom.xml lists 1.0-SNAPSHOT as the version. Thank you.
Best,
Mike

**Comment by ucagenomix** [comment]
hi mike,

yes you are right the source code in src folder is the actual Sicelore-2.0.jar file

best,
kevin
