### ISSUE TITLE
Error on NanoporeReadScanner.java

### ISSUE THREAD

**Issue by ghazaleb75** [ucagenomix/sicelore#62]
I got this error when running the whole pipeline (java version : 1.8)

<img width="1026" alt="Screen Shot 2022-02-08 at 11 55 14 AM" src="https://user-images.githubusercontent.com/71343637/153065842-21b0f8e6-2f4c-4f2a-a9e0-f83811c7dabf.png">

**Comment by ucagenomix** [comment]
we got some issue with the log4j versions in the last 2 weeks, i guess it should be solved now,
could you reclone the repo and try the quickrun.v2.sh script,
best,
