### ISSUE TITLE
ERROR: Unrecognized option: TAG while running Sicelore-2.0.jar AddGeneNameTag

### ISSUE THREAD

**Issue by rakszewska** [ucagenomix/sicelore#63]
I got the following error:
`ERROR: Unrecognized option: TAG` 
while running the following command `java -jar -Xmx12g Sicelore-2.0.jar AddGeneNameTag I=mapped_combined_sorted.bam O=/mapped_combined_sorted.GE.bam REFFLAT=refFlat.txt TAG=GE ALLOW_MULTI_GENE_READS=true USE_STRAND_INFO=true VALIDATION_STRINGENCY=SILENT`
despite following the docummentation

**Comment by ucagenomix** [comment]
please use GENETAG instead of TAG,
thanks, i will update the documentation
