### ISSUE TITLE
NanoporeBC_UMI_finder-1.0.jar speed/5'-libraries

### ISSUE THREAD

**Issue by EduardoGCCM** [ucagenomix/sicelore#64]
Hi,
First of all thank you for making this tool!

I have installed Sicelore and its dependencies and the quickrun.v2.sh file runs fine (and pretty quick). However, I when using my data (5' 10X libraries) I get stucked when using NanoporeBC_UMI_finder-1.0.jar. Even very small BAMs don't run over 24 hours. I have gone through the documentation but I don't see any obvious parameter to include in the code to ignore the poly(A) screening. Could you point it to me or confirm whether Sicelore v2 includes this option or not (I understood that v2 can be used with 5' libraries but I might be wrong)?

This is the code and output I get before it gets stucked:

> java -jar -Xmx150g sicelore/Jar/NanoporeBC_UMI_finder-1.0.jar -i tmp2/0001.sub.GEUS.bam \
-o tmp3/test_0001.sub.GEUS.bam \
-k parssed_for_ont/par.obj \
--maxUMIfalseMatchPercent 2 \
--maxBCfalseMatchPercent 5 \
--logFile NanoporeBC_UMI_finder2.log \
--ncpu 20
> +++++++   NanoporeBC_UMI_finder 1.002  Build Dec 27, 2019++++++++++++
> READING config FILE: config.xml
> Trying current working directory: /xx/config.xml
> Not found trying application root:/xx/sicelore/Jar/config.xml
> O.K. Found and using /xx/sicelore/Jar/config.xml
> Reading Illumina Data: parssed_for_ont/par.obj
> READING umi edit distances FILE: umiMaxEditDistances.xml
> Trying current working directory: /xx/umiMaxEditDistances.xml
> Not found trying application root:/xx/sicelore/Jar/umiMaxEditDistances.xml
> O.K. Found and using /xx/sicelore/Jar/umiMaxEditDistances.xml
> READING barcode edit distances FILE: bcMaxEditDistances.xml
> Trying current working directory: /xx/bcMaxEditDistances.xml
> Not found trying application root:/xx/sicelore/Jar/bcMaxEditDistances.xml
> O.K. Found and using /xx/sicelore/Jar/bcMaxEditDistances.xml
> ***** Will generate 20threads

Thank you for your help!
Eduardo

**Comment by erosix** [comment]
I have a similar issue! It is running forever and I don't have a solution.

**Comment by ucagenomix** [comment]
Hi,

a new version compatible with 10xgnoemics 5p protocol should be release asap.

best,
kevin

**Comment by EduardoGCCM** [comment]
That is great news! Do you have any idea of when this might be? 

Best,
Eduardo

**Comment by RainerWaldmann** [comment]
Hi,

The current version is only compatible with 3' barcoding. 
A new version will be released for testing within 2 - 4 weeks. Will allow 5' barcoding and BC/UMI assignment without Illumina data. 

Rainer

**Comment by EduardoGCCM** [comment]
Thanks! Will you release it in this GitHub repo or are you planning to release somewhere else first?

Looking forward to trying it out!

Best,
Eduardo

**Comment by davidebolo1993** [comment]
Hi all, 

Any updates on this ?

**Comment by EduardoGCCM** [comment]
Hi @davidebolo1993 ,
I have been able to use ONT generated pipeline. You can have a look at it here: https://github.com/nanoporetech/sockeye

I hope this helps!

**Comment by davidebolo1993** [comment]
Hi @EduardoGCCM,

I'm actually working on their nextflow port, sockeye is now dismissed.
Thanks, btw !

Davide

**Comment by erosix** [comment]
@davidebolo1993 does it mean Sockeye is not maintained anymore?

**Comment by davidebolo1993** [comment]
@erosix looks like it is not, they are implementing a nextflow version (see readme [here](https://github.com/nanoporetech/sockeye), which contains a link to the new wf-single-cell nextflow pipeline). This is under active development as far as I can tell

Best,

Davide

**Comment by ucagenomix** [comment]
Please visit Sicelore-2.1 github repository for this issue:
[https://github.com/ucagenomix/sicelore-2.1](https://github.com/ucagenomix/sicelore-2.1)
