### ISSUE TITLE
Error when running IlluminaParser.jar

### ISSUE THREAD

**Issue by yuchen345** [ucagenomix/sicelore#65]
Hi,
I'm running illuminaParser.jar with my own data and encountering the following error :
![图片](https://user-images.githubusercontent.com/71202087/158750601-4e1d8fb1-5b1d-47a6-8e03-2cbb24ded36f.png)
the command is following:
java -jar -Xmx40g Jar/IlluminaParser-1.0.jar -i possorted_genome_bam.bam -o /out/parsedForNanopore_2.obj -tbarcodes.tsv -b CB -g GN -u UB 

Any ideas what could be causing this?

Another question is whether the software is compatible with the 10x Genomics  5' kits workflow?

Hope for your reply.
Thanks, 
Zhen

**Comment by ucagenomix** [comment]
hi,
could you increase the heap space ? i.e. more than 40Gb?
A new version compatible with 10X genomics 5p should be release in the next weeks.

best,
kevin

**Comment by yuchen345** [comment]
Thank you for your help and hoping for your new release!
