### ISSUE TITLE
IsoformMatrix error for refFlatParser

### ISSUE THREAD

**Issue by chenghuihui2018** [ucagenomix/sicelore#67]
Hi, 

    I'm running IsoformMatrix with reference refFlat.txt build by myself  , the file was like this:

LOC123572819	XM_045390364.1	NC_052255.1	+	9615	14912	9615	14264	5	9615,11543,12001,13172,13518,	9737,11657,12095,13398,14912,
LOC102116409	XR_006697381.1	NC_052255.1	-	19114	20645	20645	20645	1	19114,	20645,
LOC123572833	XR_006697384.1	NC_052255.1	-	32431	35558	35558	35558	2	32431,34146,	32728,35558,
PGBD2	XM_045390416.1	NC_052255.1	-	42067	71398	42843	47350	3	42067,47333,70570,	44605,47397,71398,
PGBD2	XM_005539510.3	NC_052255.1	-	42067	60202	42843	47350	3	42067,47333,60094,	44605,47397,60202,
LOC123570995	XR_006695192.1	NC_052255.1	+	48109	48212	48212	48212	1	48109,	48212,

but I got an error log like this:
INFO	2022-04-23 23:34:36	UCSCRefFlatParser	Number of Genes Symbols	[0]
INFO	2022-04-23 23:34:36	UCSCRefFlatParser	Number of Transcripts	[0]

what could be the reason? thanks

**Comment by ucagenomix** [comment]
it seems okay to me, is this a tab-delimited file ?

**Comment by chenghuihui2018** [comment]
Yes, the file was tab-delimited. 
So, could you help me to check about it with the attachment？

**Comment by chenghuihui2018** [comment]
Yes, the file was tab-delimited.
So could you help me to check about it with the attachment I've uploaded?
[mfa.refFlat.head7w.txt](https://github.com/ucagenomix/sicelore/files/8553951/mfa.refFlat.head7w.txt)

**Comment by chenghuihui2018** [comment]
> it seems okay to me, is this a tab-delimited file ?

Yes, the file was tab-delimited.
So could you help me to check about it with the attachment I've uploaded ？thanks so much

[mfa.refFlat.head7w.txt](https://github.com/ucagenomix/sicelore/files/8553987/mfa.refFlat.head7w.txt)

@ucagenomix

**Comment by ucagenomix** [comment]
Are you using Sicelore-2.0.jar or v1 ??
i've tryed on my server and your gtf works with the v2.0:

Number of Genes Symbols [23861]
Number of Transcripts   [70000]

**Comment by chenghuihui2018** [comment]
Yes, the version I used before was v1.0. Now I‘ve updated the software to version 2.0, and It worked! Thank you for your answer


> Are you using Sicelore-2.0.jar or v1 ?? i've tryed on my server and your gtf works with the v2.0:
> 
> Number of Genes Symbols [23861] Number of Transcripts [70000]
