### ISSUE TITLE
NanoporeBC_UMI_finder-1.0.jar gets stuck

### ISSUE THREAD

**Issue by m-kuoch** [ucagenomix/sicelore#69]
Hi,

When I try to run NanoporeBC_UMI_finder-1.0.jar, the process starts but never finishes.  It gets stuck after `***** Will generate 16threads` console output.  I checked the input bam file and found that it is not empty.

In the logs I see the following:

```
Empty Drop Cell barcodes in Illumina file:1457453
+++++ INFO +++++
!!!! dynamic BC edit distance --maxBCfalseMatchPercent set --> overrides fixed UMI edit distance --bcedit defined in command line !!!!
```
Does the "Empty Drop Cell barcodes in Illumina file" mean that something is wrong?

As in issue #66, quickrun.v2.sh runs on my system but gives a different output than expected:
```
geneId	transcriptId	nbExons	nbUmis
Clta	undef	0	19
Clta	ENSMUST00000170241.7	5	21
Clta	ENSMUST00000107845.3	5	1
Clta	ENSMUST00000107847.9	6	2
Clta	ENSMUST00000107849.9	6	29

```
Thanks for the help

**Comment by kimal999** [comment]
Hi,

I have the same problem with my data. Were you able to find a solution for the problem?

**Comment by ucagenomix** [comment]
Please visit Sicelore-2.1 github repository for this issue:
[https://github.com/ucagenomix/sicelore-2.1](https://github.com/ucagenomix/sicelore-2.1)
