### ISSUE TITLE
Illuminaparser Error

### ISSUE THREAD

**Issue by abodhub** [ucagenomix/sicelore#7]
Hello, I am having an issue when running the following command on a .bam file from cellranger v2.0

` time java -Xmx15000m -jar /home/user/sicelore/Jar/IlluminaParser-1.0.jar -i /home/user/Downloads/possorted_genome_bam.bam -t /home/user/data/scdm/barcodes.tsv -o /home/user/data/javasc/output/par.obj -b CB -u UB -g GN
`

The error:

`Exception in thread "main" java.lang.ClassCastException: class java.lang.Character cannot be cast to class java.lang.String (java.lang.Character and java.lang.String are in module java.base of loader 'bootstrap')
	at com.rw.bamparsermaven.Parser.parse(Parser.java:127)
	at com.rw.bamparsermaven.Main.main(Main.java:99)
`

Also, here are few lines from the .bam file I am using:
`NB501663:146:HVFCCBGX5:2:11102:20995:14314	16	1	10486	0	14M124804N84M	*	0	0	GC[...]C	6/////E<E/A//EE//E//A//EAA/EE/EEAEEAEA/EE<AEEEEEEEEEEEEEEEEEAEEE/EEEEEEEEEEEEEEEEEEEEEEEEEEEEAAAAA	NH:i:5	HI:i:1	AS:i:84	nM:i:5	RE:A:I	CR:Z:TTCTTAGGTCAATACC	CY:Z:AAAAAEEEEEEEEEEE	CB:Z:TTCTTAGGTCAATACC-1	UR:Z:TCTTCCAGGA	UY:Z:EEEEEEEEEE	UB:Z:TCTTCCAGGA	RG:Z:count_GRCh38:MissingLibrary:1:HVFCCBGX5:2

`

Any idea what could be causing this and how to fix it?

I realise that the bam file is missing the GN tag,  but was expecting the software to recognize the missing tag. Is this the problem, or could it be something else?

**Comment by ucagenomix** [comment]
The explanation for the “java.lang.ClassCastException: class java.lang.Character cannot be cast to class java.lang.String” is, that you have one or several BAM entries that have a gene name that has just one character (quite unusual). 

A missing GN tag is no problem.

We updated the software and uploaded a new version (IlluminaParser-1.002.jar) that won’t throw an exception if a one character gene name is encountered.

**Comment by abodhub** [comment]
Great, works now! Thank you
