### ISSUE TITLE
AddBamReadSequenceTag Error

### ISSUE THREAD

**Issue by loganylchen** [ucagenomix/sicelore#70]
Hi there,

I want to try the pipeline, but encountered some issues:

When I used the demo data to addbamreadsequenceTag as below
```
java -jar Jar/Sicelore-2.0.jar AddBamReadSequenceTag I=Data/190c.clta.illumina.bam O=Data/test.bam FASTQDIR=Data/190c.clta.nanopore.reads.fq
```
Almost all the reads are not found.

Here is the logfile
```
********** NOTE: Picard's command line syntax is changing.
**********
********** For more information, please see:
********** https://github.com/broadinstitute/picard/wiki/Command-Line-Syntax-Transition-For-Users-(Pre-Transition)
**********
********** The command line looks like this in the new syntax:
**********
**********    AddBamReadSequenceTag -I Data/190c.clta.illumina.bam -O Data/test.bam -FASTQDIR Data/190c.clta.nanopore.reads.fq
**********


[Wed Jun 29 08:30:59 UTC 2022] AddBamReadSequenceTag INPUT=Data/190c.clta.illumina.bam OUTPUT=Data/test.bam FASTQDIR=Data/190c.clta.nanopore.reads.fq    SEQTAG=US QVTAG=UQ ADDQV=true VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Wed Jun 29 08:30:59 UTC 2022] Executing as root@582ec3e73010 on Linux 5.4.0-113-generic amd64; OpenJDK 64-Bit Server VM 1.8.0_312-8u312-b07-0ubuntu1~20.04-b07; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: null
INFO	2022-06-29 08:30:59	AddBamReadSequenceTag	loadFastq	START...
java.lang.NullPointerException
	at org.ipmc.sicelore.utils.FastqLoader.<init>(FastqLoader.java:50)
	at org.ipmc.sicelore.programs.AddBamReadSequenceTag.doWork(AddBamReadSequenceTag.java:48)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:303)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
	at org.ipmc.sicelore.cmdline.SiCeLoReMain.main(SiCeLoReMain.java:31)
INFO	2022-06-29 08:30:59	AddBamReadSequenceTag	loadFastq	0 reads loaded
INFO	2022-06-29 08:30:59	AddBamReadSequenceTag	addTag		START...
^CINFO	2022-06-29 08:30:59	AddBamReadSequenceTag	Error: read NB500938:149:HLH5CBGX5:1:21208:25080:10554 not found !!!
```

Looking forward to your reply.

**Comment by ucagenomix** [comment]
Hi,
FASTQDIR is a DIRECTORY, 
please provide the directory path to the fastq files,
it will load the reads present in all the files in this directory.

best

**Comment by jeneaadams** [comment]
Hi, we are trying this pipeline also with the provided data, but we also got a similar error message. Is there any insight into this issue? 

`java -jar -Xmx12g /home/stat/jiadams/yfu_lr-sc/sicelore/Jar/Sicelore-2.0.jar AddBamReadSequenceTag I=/home/stat/jiadams/yfu_lr-sc/sicelore_test/0001.sub.GE.bam O=0001.sub.GEUS.bam FASTQDIR=/home/stat/jiadams/yfu_lr-sc/sicelore_test/
samtools index 0001.sub.GEUS.bam
`

> [Tue Nov 08 15:00:34 EST 2022] AddBamReadSequenceTag INPUT=/home/stat/jiadams/yfu_lr-sc/sicelore_test/0001.sub.GE.bam OUTPUT=0001.sub.GEUS.bam FASTQDIR=/home/stat/jiadams/yfu_lr-sc/sicelore_test    SEQTAG=US QVTAG=UQ ADDQV=true VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
> [Tue Nov 08 15:00:34 EST 2022] Executing as jiadams@hpcc010.wharton.upenn.edu on Linux 3.10.0-1160.62.1.el7.x86_64 amd64; OpenJDK 64-Bit Server VM 1.8.0_332-b09; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: null
> INFO	2022-11-08 15:00:34	AddBamReadSequenceTag	loadFastq	START...
> java.lang.NullPointerException
> 	at org.ipmc.sicelore.utils.FastqLoader.<init>(FastqLoader.java:65)
> 	at org.ipmc.sicelore.programs.AddBamReadSequenceTag.doWork(AddBamReadSequenceTag.java:48)
> 	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:303)
> 	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
> 	at org.ipmc.sicelore.cmdline.SiCeLoReMain.main(SiCeLoReMain.java:31)
> INFO	2022-11-08 15:00:34	AddBamReadSequenceTag	loadFastq	53 reads loaded
> INFO	2022-11-08 15:00:34	AddBamReadSequenceTag	addTag		START...
> INFO	2022-11-08 15:00:35	AddBamReadSequenceTag	Error: read 14f18e6b-def0-40df-a303-62c1e42ad3d2 not found !!!
> INFO	2022-11-08 15:00:35	AddBamReadSequenceTag	Error: read 5e2364a2-8c76-4fec-b59c-7164e83f8ecb not found !!!
> INFO	2022-11-08 15:00:35	AddBamReadSequenceTag	Error: read 6d0e8f0c-1ae1-490b-96d7-cc164b35d5de not found !!!
> INFO	2022-11-08 15:00:35	AddBamReadSequenceTag	Error: read 9956f6e3-3ad0-44f0-b4ba-56131e2e1325 not found !!!
> INFO	2022-11-08 15:00:35	AddBamReadSequenceTag	Error: read 2db7c1ff-dd0a-4a2b-b4bd-b41b2dff540f not found !!!
> INFO	2022-11-08 15:00:35	AddBamReadSequenceTag	Error: read 41bf5058-ba6b-4858-9688-aab25475f6d5 not found !!!
> INFO	2022-11-08 15:00:35	AddBamReadSequenceTag	Error: read 14f18e6b-def0-40df-a303-62c1e42ad3d2 not found !!!
> INFO	2022-11-08 15:00:35	AddBamReadSequenceTag	Error: read 14f18e6b-def0-40df-a303-62c1e42ad3d2 not found !!!
> INFO	2022-11-08 15:00:35	AddBamReadSequenceTag	Error: read 000bb34e-814c-48dd-aae9-1ec9bfd866e5 not found !!!
> INFO	2022-11-08 15:00:35	AddBamReadSequenceTag	Error: read ecf5fa32-8197-4b21-a23e-0e3a4ff09d4d not found !!!
> INFO	2022-11-08 15:00:35	AddBamReadSequenceTag	Error: read 8a6b0dc0-8b29-4f48-8a58-e7ba728dba80 not found !!!
> INFO	2022-11-08 15:00:35	AddBamReadSequenceTag	Error: read 52237e4f-ef8d-425b-9760-1237b5063992 not found !!!
> INFO	2022-11-08 15:00:35	AddBamReadSequenceTag	Error: read 1e4ecb0a-5618-4d3a-9bf8-9c7ed4e9d76e not found !!!

**Comment by ucagenomix** [comment]
Please visit Sicelore-2.1 github repository for this issue:
[https://github.com/ucagenomix/sicelore-2.1](https://github.com/ucagenomix/sicelore-2.1)
