### ISSUE TITLE
how to deal with multi mapped reads

### ISSUE THREAD

**Issue by defendant602** [ucagenomix/sicelore#71]
A read may align to multiple transcripts and genes, and I have found a read may have different cell barcodes in primary alignment and its secondary alignment, in the bam file "GEUS10xAttributes.bam" after cell barcode and UMI assignment.

Which one is the final cell barcode of this read in this scenario? Are the secondary alignments  considered in the molecule consensus computing?  since I have found no description about secondary alignments in this repo and the publication.

By the way, are supplementary alignments considered in the molecule consensus computing?  I have found some supplementary alignments have high mapping quality and also have IG tag.

Looking forward to your reply, thanks!

**Comment by ucagenomix** [comment]
Please visit Sicelore-2.1 github repository for this issue:
[https://github.com/ucagenomix/sicelore-2.1](https://github.com/ucagenomix/sicelore-2.1)
