### ISSUE TITLE
Sicelor without matched Illumina data

### ISSUE THREAD

**Issue by mdeloger** [ucagenomix/sicelore#74]
Hi,

now that the error rate felt down with nanopore technology, is there a way to run sicelor without having matched Illumina data, please ?

Thank you for this very cool tool !

**Comment by ucagenomix** [comment]
Please visit Sicelore-2.1 github repository for this issue:
[https://github.com/ucagenomix/sicelore-2.1](https://github.com/ucagenomix/sicelore-2.1)
