### ISSUE TITLE
IsoformMatrix output 'undef' 

### ISSUE THREAD

**Issue by OdmaaBayar** [ucagenomix/sicelore#75]
Hi,

I'm working with Nanopore and Visium data and in the final isomatrix.txt output there is a high percentage (~84%) of undefined transcripts compared to an expected 30 to 50% ( https://github.com/ucagenomix/sicelore/issues/18.) I have tried running IsoformMatrix with AMBIGUOUS_ASSIGN=true and get the same results and the code does not allow me to run METHOD=SCORE ("Isoform method: [SCORE] not allowed, only STRICT method allowed (SCORE disabled)"). Is there anything upstream I can check in the analysis or flag I should try changing either during alignment or isoform expression? 

Thanks for the help!

**Comment by ucagenomix** [comment]
hi,
high undef means low full-length cDNA, you could have a look at your bam file you should see missing 5'part of the transcripts so sicelore can not assign an isoform unambigously. Working with the junction matrix is a possibility to detect differentially expressed junction that might be specific to an isoform.

**Comment by OdmaaBayar** [comment]
Thank you @ucagenomix.
Is there a way to get the SCORE method to work in this case?
