### ISSUE TITLE
poa from bioconda does not work

### ISSUE THREAD

**Issue by dkoppstein** [ucagenomix/sicelore#8]
Thanks for creating the software. I just wanted to report that I couldn't get quickrun.sh to run when using poa=2.0=h516909a_2 from bioconda, it always stalled at ComputeConsensus step. This was solved when I went reinstalled poa using the build from tanghaibio/bio-pipeline. It would be useful to solve this, since a lot of people use bioconda, and then you can just provide an environment.yaml file to go with the software. 

Thanks!
David

P.S. do you plan to release the source code?

**Comment by AshDangerByrne** [comment]
Hi, I had the same issue regarding poa. It stalled on me and I had to reinstall using the poa from tanghaibio/bio-pipeline which solved the issue. It would be useful to maybe even incorporate spoa. It would be great to get access to the source code. 

Thanks,
Ashley Byrne

**Comment by ucagenomix** [comment]
Hi, you can give a try to the Sicelore-2.0.jar version which do use spoa and generate fastq consensus sequence file to keep track of QV values for SNV calling in next steps (if required). I'm planning to release the source code, at least for sicelore dev, in the next few weeks. Cheers, kevin
