### ISSUE TITLE
Unable to generate SNP Matrix 

### ISSUE THREAD

**Issue by ahawkins1992** [ucagenomix/sicelore#9]
Hello, 

I am trying to generate my SNP matrix, but the result is an empty matrix where only the columns with geneID, transcriptID, and then each cell barcode is output. There is no row for each of the SNPs that I am inputting into my csv. 

This is the example of the script that I am running: 

java -jar -Xmx100g /gpfs/commons/home/ahawkins/sicelore/Jar/Sicelore-1.0.jar SNPMatrix I=y1_lin_ont_got_tp53_consensus.tags_v3.bam CSV=barcodes.csv SNP=/gpfs/commons/groups/landau_lab/ST_GoT/ONT_GoT_TP53_031120/tp53_snps.csv RN_min=0 O=tp53_linear_got_output PREFIX=tp53_got_barcodes

This is the input SNP file: 
name,gene,chromosome,start,end,strand,pos,ref,alt
rs1042522,TP53,chr17,7666402,7689550,+,7676154,G,C

Any insight on why this would be the case? Even if the SNV wasn't present wouldn't there be a row with the SNV name and then 0's for it not being detected in any of the cells? 

Thank you!

**Comment by ucagenomix** [comment]
I'm currenly working on this part of the pipeline, we should release a new version of SNPMatrix in the next few days. Any thought is very welcome to improve. You're right if no molecule is covering SNV position the position won't be in the output file, maybe better to have it anyway. When you look at the SNV position in your bam file do you see any molecule for any cell from barcodes.csv ? If you see at least  one molecule there should be at least one count and the position should be in the output. 

You can check that there is no difference in reference naming between snps.csv and bam file (check header, chr17 versus 17 for instance).

BTW, not an easy positon for SNV calling in nanopore reads... "GGGGGG", what is your avg reads per molecules ?

**Comment by ahawkins1992** [comment]
This is a targeting sequencing approach, so average reads are > 1000. 

So are you saying that would or would not have a row for an SNV even if it wasn't detected in any cell? I would think it would be helpful to have a way to distinguish between a SNV that wasn't detected vs. thinking the output could not be correct. 

My bam file has 410 instances of the position that I am looking for, so I would anticipate that it should be callable?

**Comment by ahawkins1992** [comment]
This is the output file that is generated from running the SNP Matrix command, if this helps: 

INFO    2020-03-23 17:09:05     SNPMatrix       Cells detected                  [2255]
INFO    2020-03-23 17:09:05     SNPMatrix               processing...           <U+FEFF>name,gene,chromosome,start,end,strand,pos,ref,alt
java.lang.NumberFormatException: For input string: "start"
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.base/java.lang.Integer.parseInt(Integer.java:652)
        at java.base/java.lang.Integer.parseInt(Integer.java:770)
        at org.ipmc.sicelore.programs.SNPMatrix.doWork(SNPMatrix.java:107)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:277)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
        at org.ipmc.sicelore.cmdline.SiCeLoReMain.main(SiCeLoReMain.java:40)
[Mon Mar 23 17:09:06 EDT 2020] org.ipmc.sicelore.programs.SNPMatrix done. Elapsed time: 0.01 minutes.

**Comment by ucagenomix** [comment]
try to remove the header line of the input SNP file and rerun, it should works.

**Comment by ahawkins1992** [comment]
I am still getting the same output where it is just the headers of the column but this is now my log file: 
INFO    2020-03-23 18:18:11     SNPMatrix       Cells detected                  [2255]
INFO    2020-03-23 18:18:11     SNPMatrix               processing...           <U+FEFF>rs1042522,TP53,chr17,7666402,7689550,+,7676154,G,C

with no more errors so that is working...

**Comment by ahawkins1992** [comment]
Figured it out, the strand was wrong, thank you for your help!
